apiVersion: kafka.strimzi.io/v1beta1
kind: KafkaTopic
metadata:
  name: eventos-negocio-mensagem
  labels:
    strimzi.io/cluster: kafka
spec:
  partitions: 3
  replicas: 2
  config:
    retention.ms: -1