---
apiVersion: v1
kind: Service
metadata:
  name: {{ template "mensagem-backend.fullname" . }}-kamon
  labels:
    app: {{ template "mensagem-backend.name" . }}
    chart: {{ template "mensagem-backend.chart" . }}
    monitor: kamon
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  serviceAccountName: {{ .Values.serviceAccount }}
  type: ClusterIP
  #clusterIP: None
  ports:
    - port: 9095
      targetPort: kamon
      protocol: TCP
      name: kamon
  selector:
    app: {{ template "mensagem-backend.name" . }}
    release: {{ .Release.Name }}
 
